using System.Collections.Generic;

namespace Entities
{
    public class PorductList
    {
        public string id { get; set; }
        public string productCode { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public string product_type { get; set; }
        public string barcode { get; set; }
        public string gtin { get; set; }
        public string send_api { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public string group { get; set; }
        public string quantity { get; set; }
        public string currencyType { get; set; }
        public string kdv_id { get; set; }
        public string price1 { get; set; }
        public string price2 { get; set; }
        public string price3 { get; set; }
        public string price4 { get; set; }
        public string price5 { get; set; }
        public string price6 { get; set; }
        public string price7 { get; set; }
        public string price8 { get; set; }
        public string n11_price { get; set; }
        public string n11_discountValue { get; set; }
        public string hb_price { get; set; }
        public string trendyol_listPrice { get; set; }
        public string trendyol_salePrice { get; set; }
        public string eptt_price { get; set; }
        public string eptt_iskonto { get; set; }
        public string n11pro_price { get; set; }
        public string n11pro_discountValue { get; set; }
        public string amazon_price { get; set; }
        public string amazon_salePrice { get; set; }
        public string mizu_price1 { get; set; }
        public string mizu_price2 { get; set; }
        public string zebramo_listPrice { get; set; }
        public string zebramo_salePrice { get; set; }
        public string farmazon_price { get; set; }
        public string farmazon_market_price { get; set; }
        public string farmaBorsaPrice { get; set; }
        public string farmaborsa_psPrice { get; set; }
        public string morhipo_listPrice { get; set; }
        public string morhipo_salePrice { get; set; }
        public string lidyana_listPrice { get; set; }
        public string lidyana_salePrice { get; set; }
        public string pazarama_listPrice { get; set; }
        public string pazarama_salePrice { get; set; }
        public string vfmall_listPrice { get; set; }
        public string vfmall_salePrice { get; set; }
        public string aliniyor_listPrice { get; set; }
        public string aliniyor_salePrice { get; set; }
        public string aliexpress_price { get; set; }
        public string aliexpress_salePrice { get; set; }
        public string modanisa_listPrice { get; set; }
        public string modanisa_salePrice { get; set; }
        public string bpazar_price1 { get; set; }
        public string bpazar_price2 { get; set; }
        public string flo_listPrice { get; set; }
        public string flo_salePrice { get; set; }
        public string novadan_price { get; set; }
        public string needion_listPrice { get; set; }
        public string needion_salePrice { get; set; }
        public string bisifirat_listPrice { get; set; }
        public string bisifirat_salePrice { get; set; }
        public string iyifiyat_listPrice { get; set; }
        public string iyifiyat_salePrice { get; set; }
        public string turkcellpasaj_listPrice { get; set; }
        public string turkcellpasaj_salePrice { get; set; }
        public string narwoo_price { get; set; }
        public string narwoo_salePrice { get; set; }
        public string joom_price { get; set; }
        public string joom_msrPrice { get; set; }
        public string nevade_listPrice { get; set; }
        public string nevade_salePrice { get; set; }
        public string yapisepeti_listPrice { get; set; }
        public string yapisepeti_salePrice { get; set; }
        public string op1001_listPrice { get; set; }
        public string op1001_salePrice { get; set; }
        public string etsy_price { get; set; }
        public string wish_price { get; set; }
        public string omnitron_price1 { get; set; }
        public string omnitron_price2 { get; set; }
        public string zoodmall_price { get; set; }
        public string buying_price { get; set; }
        public string supplier { get; set; }
        public string date_change { get; set; }
        public string date_add { get; set; }
        public string hb_sku { get; set; }
        public string mpn { get; set; }
        public string alan1 { get; set; }
        public string alan2 { get; set; }
        public string alan3 { get; set; }
        public string alan4 { get; set; }
        public string alan5 { get; set; }
        public List<Variatio> variatios { get; set; }
        public List<Picture> pictures { get; set; }
    }
}